export const EGYPTIAN_DRUGS = [
  "Augmentin 1g Tablets", "Augmentin 625mg Tablets", "Augmentin 457mg Suspension", "Augmentin 312mg Suspension",
  "Panadol Advance 500mg", "Panadol Extra", "Panadol Cold & Flu", "Panadol Joint", "Panadol Sinus", "Panadol Night",
  "Brufen 400mg Tablets", "Brufen 600mg Tablets", "Brufen 200mg Tablets", "Brufen Syrup", "Brufen Retard 800mg",
  "Cataflam 50mg Tablets", "Cataflam 25mg Tablets", "Catafly Suspension", "Cataflam Drops",
  "Voltaren 50mg Tablets", "Voltaren 75mg Injection", "Voltaren 100mg Suppositories", "Voltaren Emulgel",
  "Congestal Tablets", "Congestal Syrup", "1,2,3 Tablets", "1,2,3 Syrup", "Comtrex Tablets",
  "Amoxicillin 500mg Capsules", "Amoxil 500mg Capsules", "Amoxil 250mg Suspension",
  "Hibiotic 1g Tablets", "Hibiotic 625mg Tablets", "Hibiotic 460mg Suspension",
  "Megamox 1g Tablets", "Megamox 625mg Tablets", "Megamox 457mg Suspension",
  "Flumox 500mg Capsules", "Flumox 1g Tablets", "Flumox 250mg Capsules", "Flumox Syrup",
  "Zithromax 500mg Tablets", "Zithromax 200mg Suspension", "Xithrone 500mg Tablets", "Xithrone Suspension",
  "Ciprocin 500mg Tablets", "Ciprocin 750mg Tablets", "Ciprofar 500mg Tablets",
  "Tavanic 500mg Tablets", "Levanic 500mg Tablets", "Levoxin 500mg Tablets",
  "Flagyl 500mg Tablets", "Flagyl 250mg Tablets", "Flagyl Suspension",
  "Amrizole 500mg Tablets", "Amrizole 250mg Tablets", "Amrizole Suspension", "Amrizole Suppositories",
  "Antinal Capsules", "Antinal Suspension", "Diax Capsules",
  "Streptoquin Tablets", "Streptoquin Suspension",
  "Visceralgin Tablets", "Visceralgin Injection", "Visceralgin Suppositories", "Visceralgin Syrup",
  "Spasmocanulase Tablets", "Spasmopyrulgin Injection", "Spasmo-Digestin Tablets",
  "Colona Tablets", "Coloverin A Tablets", "Coloverin D Tablets", "Coloverin SR Capsules",
  "Librax Tablets", "Gast-Reg 200mg Tablets", "Gast-Reg 100mg Tablets",
  "Motilium 10mg Tablets", "Motilium Suspension", "Motinorm Tablets",
  "Nexium 40mg Tablets", "Nexium 20mg Tablets", "Controloc 40mg Tablets", "Controloc 20mg Tablets",
  "Pantoloc 40mg Tablets", "Antodine 20mg Tablets", "Antodine 40mg Tablets",
  "Gaviscon Syrup", "Gaviscon Advance Syrup", "Maalox Plus Suspension", "Maalox Chewable Tablets",
  "Epicogel Suspension", "Moxal Plus Suspension",
  "Zyrtec 10mg Tablets", "Zyrtec Drops", "Zyrtec Syrup",
  "Telfast 120mg Tablets", "Telfast 180mg Tablets", "Telfast Suspension",
  "Claritine 10mg Tablets", "Claritine Syrup", "Mosidin 10mg Tablets",
  "Aerius 5mg Tablets", "Aerius Syrup", "Levhistam 5mg Tablets", "Levhistam Syrup",
  "Eltroxin 50mcg Tablets", "Eltroxin 100mcg Tablets", "Thyrox 50mcg Tablets",
  "Glucophage 500mg Tablets", "Glucophage 1000mg Tablets", "Glucophage XR 1000mg", "Glucophage XR 500mg",
  "Amaryl 2mg Tablets", "Amaryl 3mg Tablets", "Amaryl 4mg Tablets",
  "Diamicron MR 60mg", "Diamicron MR 30mg", "Diamicron 80mg",
  "Janumet 50/1000mg", "Janumet 50/500mg", "Galvus Met 50/1000mg", "Galvus Met 50/850mg",
  "Concor 5mg Tablets", "Concor 10mg Tablets", "Concor Plus 5/12.5mg", "Concor 2.5mg Tablets",
  "Capoten 25mg Tablets", "Capoten 50mg Tablets", "Capozide Tablets",
  "Exforge 5/160mg", "Exforge 10/160mg", "Exforge HCT", "Tarka Tablets",
  "Plavix 75mg Tablets", "Aspirin Protect 100mg", "Aspocid 75mg Tablets", "Aggrex 75mg Tablets",
  "Clexane 40mg Injection", "Clexane 60mg Injection", "Clexane 80mg Injection",
  "Lipitor 20mg Tablets", "Lipitor 40mg Tablets", "Lipitor 10mg Tablets",
  "Crestor 10mg Tablets", "Crestor 20mg Tablets", "Rosuvastatin 10mg", "Ator 20mg Tablets", "Ator 40mg Tablets",
  "Neuroton Ampoules", "Neuroton Tablets", "Depovit B12 Injection", "Betolvex Injection", "Tri-B Injection",
  "Milga Tablets", "Milga Advance Tablets", "Thiotech 600mg Tablets", "Thiotacid 600mg Tablets", "Neurorubine Forte Tablets",
  "Lyrica 75mg Capsules", "Lyrica 150mg Capsules", "Lyrica 300mg Capsules", "Pregavalex 75mg",
  "Tegretol 200mg Tablets", "Tegretol CR 400mg", "Depakine Chrono 500mg", "Depakine Syrup",
  "Keppra 500mg Tablets", "Keppra 1000mg Tablets",
  "Cipralex 10mg Tablets", "Cipralex 20mg Tablets", "Seroxat 20mg Tablets", "Seroxat CR 25mg",
  "Lustral 50mg Tablets", "Prozac 20mg Capsules", "Philozac 20mg Capsules",
  "Xanax 0.25mg Tablets", "Xanax 0.5mg Tablets", "Calmepam 1.5mg Tablets", "Calmepam 3mg Tablets",
  "Dormicum 15mg Tablets", "Dormicum 7.5mg Tablets",
  "Viagra 50mg Tablets", "Viagra 100mg Tablets", "Cialis 20mg Tablets", "Joypox 60mg Tablets",
  "Dafrex 500mg Tablets", "Daflon 500mg Tablets", "Diosmin 500mg Tablets", "Venoruton Tablets",
  "Reparil 40mg Tablets", "Alphintern Tablets", "Ambezym Tablets", "Maxilase Syrup",
  "Mucosolvan Syrup", "Prospan Syrup", "Opecto Syrup", "Bronchicum Syrup", "Sinecod Syrup", "Sinecod Drops", "Selgon Drops/Tablets",
  "Avamys Nasal Spray", "Flixonase Nasal Spray", "Nasonex Nasal Spray", "Nazomac Nasal Spray",
  "Otrivin Adult Drops", "Otrivin Baby Saline", "Otrivin Menthol Spray", "Afrin Nasal Spray",
  "Betadine Mouth Wash", "Betadine Gargle", "Ora-Cure Gel", "Miconaz Oral Gel", "Daktarin Oral Gel",
  "Fucidin Cream", "Fucidin Ointment", "Fucicort Cream", "Kenacomb Cream", "Garamycin Cream", "Betaderm Ointment",
  "Terbin 1% Cream", "Lamisil 1% Cream", "Lamisil Spray", "Dermatin Cream",
  "Voltaren Emulgel", "Reparil Gel N", "Fastum Gel", "Moov Massage Cream", "Rubalgine Cream",
  "Systane Ultra Drops", "Refresh Tears Drops", "Tobradex Eye Drops", "Tobradex Ointment",
  "Vigamox Eye Drops", "Dexatobrin Eye Drops", "Hyfresh Eye Drops", "Polyfresh Eye Drops",
  "Optive Eye Drops", "Ciprodar Eye Drops", "Nevanac Eye Drops", "Xalatan Eye Drops",
  "Cosopt Eye Drops", "Alphagan P Eye Drops", "Vi-Drops", "Dexaflox Eye Drops",
  "Elocon Cream", "Elocon Ointment", "Elocon Lotion",
  "Roaccutane 20mg Capsules", "Roaccutane 10mg Capsules", "Netlook 20mg Capsules", "Isotretinoin 20mg",
  "Aldactone 25mg Tablets", "Aldactone 100mg Tablets", "Lasix 40mg Tablets", "Lasix Ampoules",
  "Epanutin 100mg Capsules", "Dilantin Suspension",
  "Ursofalk 250mg Capsules", "Ursogall 250mg Capsules",
  "Rowatinex Capsules", "Proximol Tablets", "Urivin Effervescent",
  "Feroglobin Capsules", "Feroglobin Syrup", "Haemoton Capsules", "Fero-6 Capsules",
  "Centrum Lutein Tablets", "Maddovit Tablets", "Osteocare Tablets", "Calcical Tablets",
  "Vidrop Drops", "Devarol Injection",
  "Genuphil Tablets", "Dorofen Capsules", "Chondro-Gen Capsules",
  "Prostec Capsules", "Tamsulin 0.4mg Capsules", "Omnic Ocas 0.4mg",
  "Duspatalin Retard 200mg", "Duspatalin 135mg", "Mebeverine 200mg",
  "Ketofan 50mg Capsules", "Ketolac 30mg Ampoules", "Ketolac Tablets"
].sort();
